### ISSUE TITLE
UCSC chromInfo.txt parsing error

### ISSUE THREAD

**Issue by iromeo** [superbobry/big#11]
This is the head of chromInfo.txt (ungzip UCSC annotation file) file: 

```
chr1    249250621       /gbdb/hg19/hg19.2bit
chr2    243199373       /gbdb/hg19/hg19.2bit
chr3    198022430       /gbdb/hg19/hg19.2bit
```

BigWig parses  it using

```
val chunks = line.split('\t', limit = 2)
BPlusLeaf(chunks[0], i, chunks[1].toInt())
```

So I get chunks = {"chr1", " 249250621\t/gbdb/hg19/hg19.2bit"} and exception while evaluating `chunks[1].toInt()`

**Comment by superbobry** [comment]
You should've used `hg19.chrom.sizes` instead of `chromInfo.txt`. But I've changed the code to support both formats anyway :)
