### ISSUE TITLE
Single ScoredInterval in wig and tdf

### ISSUE THREAD

**Issue by olegs** [superbobry/big#21]

**Comment by superbobry** [comment]
Wig already had one before tdf, yep :)

**Comment by olegs** [comment]
WigInterval in tdf looks confusing.
20 нояб. 2015 г. 11:07 AM пользователь "Sergei Lebedev" <
notifications@github.com> написал:

**Comment by superbobry** [comment]
Done in d4ea268444e4b1b97faab2b073a88e9af513c23a.
