### ISSUE TITLE
IllegalStateException: impossible "browser" section type in *.wig file

### ISSUE THREAD

**Issue by iromeo** [superbobry/big#30]
Occurs in big-0.3.5-sources.jar!/org/jetbrains/bio/big/Wig.kt:64
"browser" is considered as impossible section
```
$ head -n 20 YD1_CpG.wig
browser position chr1:1-135534747
browser hide all
browser pack refGene cpgIslandExt
track type=wiggle_0 name="YD1 methCpG" visibility=full color=190,0,0 autoScale=off viewLimits=0.0:100.0 yLineMark=0.0 yLineOnOff=on maxHeightPixels=75:75:20 priority=01
variableStep chrom=chr1
10497	86.009
10525	88.684
10542	99.500
133165	90.000
133180	100.000
134999	100.000
135028	91.892
135031	91.667
136876	100.000
136895	100.000
136911	94.545
136913	96.364
136925	0.000
137120	100.000
137157	81.818
```

`WigFile(wigPath)` leads to:
```
Caused by: java.lang.IllegalStateException
	at org.jetbrains.bio.big.WigIterator.cache(Wig.kt:377)
	at org.jetbrains.bio.big.WigIterator.cache(Wig.kt:32)
	at org.jetbrains.bio.CachingIterator.hasNext(Support.kt:86)
```

**Comment by iromeo** [comment]
@superbobry May be it is better to skip not supported sections?

```
# ig-0.3.5-sources.jar!/org/jetbrains/bio/big/Wig.kt:64
when (type) {
                        "track" -> check(params["type"] == "wiggle_0")
                        "variableStep" -> state = State.VARIABLE_STEP
                        "fixedStep" -> state = State.FIXED_STEP
                        else -> impossible()
                    }
```

**Comment by superbobry** [comment]
My personal preference would be to explicitly enumerate them before else instead of skipping anything we don't expect. But I don't mind if you go the other way :)

**Comment by iromeo** [comment]
@superbobry ok, at first I need to look through specification, if any custom sections are possible, then skip all unsupported, else we can hardcode list of valid options.

**Comment by iromeo** [comment]
Not clear from specification, mentioned only in examples https://genome.ucsc.edu/goldenpath/help/wiggle.html and as "browser line" in https://genome.ucsc.edu/goldenpath/help/customTrack.html#TRACK. So let's ignore only "browser" sections
