### ISSUE TITLE
Logging is too aggressive: AutoSQL queries are unsupported

### ISSUE THREAD

**Issue by olegs** [superbobry/big#32]
To reproduce open chromhmm file: https://encodeproject.org/files/ENCFF564DYK/@@download/ENCFF564DYK.bigBed
I see tons of message in logs.

[2017-11-09 17:35:29] BigFile [WARN] AutoSQL queries are unsupported
See https://github.com/JetBrains-Research/epigenome/issues/1091 for details.

**Comment by iromeo** [comment]
Fixed in 0.5.1. See Issue #7
