### ISSUE TITLE
Mention the library at https://research.jetbrains.org/groups/biolabs

### ISSUE THREAD

**Issue by iromeo** [superbobry/big#46]
Write a description for the library for https://research.jetbrains.org/groups/biolabs

**Comment by iromeo** [comment]
It is already mentioned in https://research.jetbrains.org/groups/biolabs/projects, but not in "Tools" section at https://research.jetbrains.org/groups/biolabs

**Comment by olegs** [comment]
What kind of mentioning is supposed? Please clarify since it is already mentioned on the group webpage.

**Comment by iromeo** [comment]
The issue is old enough and web site was significantly redesign since I’ve filled it, so it isn’t applicable for the current design and is resolved.
