### ISSUE TITLE
Why do we need com.indeed.util-mmap 

### ISSUE THREAD

**Issue by dievsky** [superbobry/big#50]
So we have `com.indeed.util-mmap` as a compile dependency. However, it seems to only be used in `MMBRomBuffer` and `MMBRomBufferFactory` classes, which in turn seem to be only used in tests.

The reason I'm asking is because of the failing tests. And the tests are failing because `com.indeed.util-mmap` only supports a couple architectures, so any attempt to run tests on Windows or FreeBSD fails.

Does anyone know / remember why did we need this dependency? Was it used in the actual code before, and then removed?

(Assigning @iromeo as the most likely person to know the answer.)

**Comment by iromeo** [comment]
@dievsky

> Does anyone know / remember why did we need this dependency? Was it used in the actual code before, and then removed?

>, which in turn seem to be only used in tests.

The big library provides public API for users, so it is expected that some API is used inside the library in tests only, but it could be used as a public API outside the library by users. 

The library entry point `BigFile.read(src, prefetch, cancelledChecker, factoryProvider)` allows using different memory buffer implementations. The default one is using slower random access files (supports both Windows, Linux), the faster impl `MMBRomBufferFactory` is based on RAM mapped files, so works much faster.

> only supports a couple architectures

Yes, according to the CHANGELOG
```
Version 0.7.0
-------------

Released on March 30th 2018

Fixed
- RandomAccessFile (https://www.unidata.ucar.edu) copied to project and
  rewritten in Kotlin so as not to depend on heavy netcdf-java library.
  For simplicity writing operations were removed from file.

- Windows support #36, using RandomAccessFile
 (https://www.unidata.ucar.edu/software/thredds/v4.3/netcdf-java project)
 instead of memory mapped buffer. The previous impl (works only on
 Mac/Linux) is available using `MMBRomBufferFactory` in `Big*.read()`.
 ```
 `MMBRomBufferFactory` is not available on Windows. At the moment `RandomAccessFile` is used as the default impl.
 
 > The reason I'm asking is because of the failing tests
>  so any attempt to run tests on Windows or FreeBSD fails.

It isn't true, windows tests are working OK at https://teamcity.jetbrains.com/buildConfiguration/Epigenome_Tools_BigWindows

So if the question is about tests, then tests could be succesfully launched on Windows.

**Comment by iromeo** [comment]
As for supporting `MMBRomBufferFactory` it is hard to say should we drop it or not. It was an initial impl and it could be useful and provide significant speedup in some use cases, but at the moment RandomAccessFiles performance is ok in JBR browser. Moreover `MMBRomBufferFactory` requires high RAM usage so we cannot keep opened many BigWig files at the same time, so we don't use it in JBR.

Theoretically, we could drop it in the next major update, but running tests on Windows seems to be not related to this dependency.

**Comment by dievsky** [comment]
@iromeo thanks for the clarification, now I have more understanding of the subject. Now I realize that I should have checked the supertype usages as well.

Re: failing tests -- yes, I've typed too hastily. The tests have a specific check which excludes testing the `mmap` on Windows. It does not, however, check for FreeBSD, or arm64, or anything else not supported by `mmap`. Which is why the tests I had set up on the internal build server have failed.

To deal with that, we should adapt the tests to not just exclude `mmap` for Windows, but rather to include it only for the three supported arch/OS combinations. This will also help anyone who decides to build `big` from sources on their smartphone.

**Comment by dievsky** [comment]
So I'm marking this as a bug, because the Windows check is not sufficient.

**Comment by dievsky** [comment]
I've replaced the check, should get better now.

**Comment by dievsky** [comment]
Everything seems to work for now, closing.
